In [1]:
import pandas as pd
import requests

In [2]:
url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkMmRkNjU0ZmFiOTU2Zjk0ZDRlODA1NTg0OGJlYzg1YyIsIm5iZiI6MTc2ODg4NTAxMy42NDcsInN1YiI6IjY5NmYwYjE1Y2YzY2JkMjBiNmRmMGJlMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WsEbv3ydfM8QyLKXK4vyjTFAWPUbbabyao19317bNqA"
}

response = requests.get(url, headers=headers)

#print(response.text)

In [3]:
response.json

In [14]:
#response.json()

In [4]:
response.json()['results'] #fetch only results key values that gives me a list in which there are various dictionaries

[{'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 28.8668,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'title': 'The Shawshank Redemption',
  'video': False,
  'vote_average': 8.7,
  'vote_count': 29558},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 35.7668,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'title': 'The Godfather',
  'video': False,
  'vote_average': 8.686,
  'vote_count': 22317},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 19.6783,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'title': 'The Godfather Part II',
  'video': False,
  'vote_average': 8.57,
  'vote_count': 13495},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 13.8958,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'title': "Schindler's List",
  'video': False,
  'vote_average': 8.565,
  'vote_count': 17009},
 {'adult': False,
  'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
  'genre_ids': [18],
  'id': 389,
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 11.0349,
  'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
  'release_date': '1957-04-10',
  'title': '12 Angry Men',
  'video': False,
  'vote_average': 8.552,
  'vote_count': 9664},
 {'adult': False,
  'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 18.2633,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'title': 'Spirited Away',
  'video': False,
  'vote_average': 8.533,
  'vote_count': 17850},
 {'adult': False,
  'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
  'genre_ids': [18, 28, 80, 53],
  'id': 155,
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 24.2132,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'title': 'The Dark Knight',
  'video': False,
  'vote_average': 8.525,
  'vote_count': 35016},
 {'adult': False,
  'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 6.7217,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-20',
  'title': 'Dilwale Dulhania Le Jayenge',
  'video': False,
  'vote_average': 8.518,
  'vote_count': 4541},
 {'adult': False,
  'backdrop_path': '/lgJlu0Fp1mdTaFEeaQJ7DskhSOr.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 19.416,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'title': 'The Green Mile',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 18737},
 {'adult': False,
  'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 25.8205,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'title': 'Parasite',
  'video': False,
  'vote_average': 8.496,
  'vote_count': 19982},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 23.0537,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'title': 'The Lord of the Rings: The Return of the King',
  'video': False,
  'vote_average': 8.5,
  'vote_count': 25884},
 {'adult': False,
  'backdrop_path': '/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 18.9006,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'title': 'Pulp Fiction',
  'video': False,
  'vote_average': 8.486,
  'vote_count': 29556},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 20.449,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'title': 'Your Name.',
  'video': False,
  'vote_average': 8.479,
  'vote_count': 12231},
 {'adult': False,
  'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
  'genre_ids': [37],
  'id': 429,
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 13.9707,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-22',
  'title': 'The Good, the Bad and the Ugly',
  'video': False,
  'vote_average': 8.468,
  'vote_count': 9355},
 {'adult': False,
  'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 47.32,
  'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  'release_date': '2014-11-05',
  'title': 'Interstellar',
  'video': False,
  'vote_average': 8.466,
  'vote_count': 38653},
 {'adult': False,
  'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 13,
  'original_language': 'en',
  'original_title': 'Forrest Gump',
  'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
  'popularity': 18.7006,
  'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
  'release_date': '1994-06-23',
  'title': 'Forrest Gump',
  'video': False,
  'vote_average': 8.462,
  'vote_count': 29115},
 {'adult': False,
  'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
  'genre_ids': [18, 80],
  'id': 769,
  'original_language': 'en',
  'original_title': 'GoodFellas',
  'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
  'popularity': 15.3964,
  'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
  'release_date': '1990-09-12',
  'title': 'GoodFellas',
  'video': False,
  'vote_average': 8.452,
  'vote_count': 13924},
 {'adult': False,
  'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
  'genre_ids': [28, 18],
  'id': 346,
  'original_language': 'ja',
  'original_title': '七人の侍',
  'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  'popularity': 7.5602,
  'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
  'release_date': '1954-04-26',
  'title': 'Seven Samurai',
  'video': False,
  'vote_average': 8.45,
  'vote_count': 4084},
 {'adult': False,
  'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg',
  'genre_ids': [16, 18, 10752],
  'id': 12477,
  'original_language': 'ja',
  'original_title': '火垂るの墓',
  'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
  'popularity': 0.0084,
  'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
  'release_date': '1988-04-16',
  'title': 'Grave of the Fireflies',
  'video': False,
  'vote_average': 8.4,
  'vote_count': 6286},
 {'adult': False,
  'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
  'genre_ids': [35, 18],
  'id': 637,
  'original_language': 'it',
  'original_title': 'La vita è bella',
  'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
  'popularity': 9.0641,
  'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
  'release_date': '1997-12-20',
  'title': 'Life Is Beautiful',
  'video': False,
  'vote_average': 8.44,
  'vote_count': 13732}]

In [5]:
# now this list needs to convert in dataframes and pass the list in this dataframe
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,28.8668,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,29558
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",35.7668,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.686,22317
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,19.6783,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.570,13495
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,13.8958,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,17009
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,11.0349,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.552,9664
5,False,/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",18.2633,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,Spirited Away,False,8.533,17850
6,False,/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,24.2132,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.525,35016
7,False,/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",6.7217,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.518,4541
8,False,/lgJlu0Fp1mdTaFEeaQJ7DskhSOr.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,19.4160,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.500,18737
9,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",25.8205,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.496,19982
10,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,23.0537,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,The Lord of the Rings: The Return of the King,False,8.500,25884
11,False,/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg,"[53, 80, 35]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",18.9006,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,Pulp Fiction,False,8.486,29556
12,False,/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,20.4490,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.479,12231
13,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,13.9707,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.468,9355
14,False,/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,47.3200,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.466,38653
15,False,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,18.7006,/saHP97rTPS5eLmrLQEcANmKrsFl.jpg,1994-06-23,Forrest Gump,False,8.462,29115
16,False,/gILte6Zd7m1YneIr6MVhh30S9pr.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",15.3964,/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg,1990-09-12,GoodFellas,False,8.452,13924
17,False,/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,7.5602,/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg,1954-04-26,Seven Samurai,False,8.450,4084
18,False,/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.0084,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.400,6286
19,False,/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg,"[35, 18]",637,it,La vita è bella,A touching story of an Italian book seller of ...,9.0641,/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg,1997-12-20,Life Is Beautiful,False,8.440,13732

In [6]:
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,28.8668,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.700,29558
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",35.7668,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.686,22317

In [7]:
# but it is giving me all the columns but needs some specific coloumns only
df = pd.DataFrame(response.json()['results'])[['id', 'title', 'release_date', 'overview', 'popularity', 'vote_average', 'vote_count']]

In [8]:
df.head()

,id,title,release_date,overview,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,1994-09-23,Imprisoned in the 1940s for the double murder ...,28.8668,8.700,29558
1,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",35.7668,8.686,22317
2,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,19.6783,8.570,13495
3,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,13.8958,8.565,17009
4,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,11.0349,8.552,9664

In [24]:
# now we need to run this code in a loop
# this loop will run for 531 times i.e., the no. of pages
# after fetching data from each page it should append the data 
#finally we have complete dataset
# to store this first we needs to create an emplty dataframe
df = pd.DataFrame()  # empty dataframe

In [25]:
df

Empty DataFrame
Columns: []
Index: []

In [9]:
import requests
import pandas as pd

df = pd.DataFrame()

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkMmRkNjU0ZmFiOTU2Zjk0ZDRlODA1NTg0OGJlYzg1YyIsIm5iZiI6MTc2ODg4NTAxMy42NDcsInN1YiI6IjY5NmYwYjE1Y2YzY2JkMjBiNmRmMGJlMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.WsEbv3ydfM8QyLKXK4vyjTFAWPUbbabyao19317bNqA"
}

for i in range(1, 100):  # Pages 1 to 531
    url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"

    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        temp_df = pd.DataFrame(response.json()['results'])[
            ['id', 'title', 'release_date', 'overview',
             'popularity', 'vote_average', 'vote_count']
        ]

        df = pd.concat([df, temp_df], ignore_index=True)
    else:
        print(f"Failed at page {i}, status code: {response.status_code}")

print(df.head())

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [41]:
df.shape

(1980, 7)

In [42]:
df.to_csv('toprated.csv')