# 🐼 Pandas - Introduction & Setup
Welcome to your first part of **Pandas**. In this session, we'll learn what Pandas is, why we use it, and how to get started with Series and DataFrames.

## 1 What is Pandas and Why Use It?
Pandas is a powerful **Python library** for data analysis and manipulation.

Key points:
- Provides two main data structures: **Series** (1D) and **DataFrame** (2D).
- Makes working with tabular data easy and fast.
- Ideal for cleaning, transforming, and analyzing datasets.
- Works well with other libraries like NumPy, Matplotlib, and Scikit-Learn.

## 2 Installing & Importing Pandas
To install pandas, open your terminal or command prompt and run:
```bash
pip install pandas
```
Then, you can import it in Python as follows:

## 3 Understanding Series & DataFrame
- **Series**: One-dimensional labeled array, like a column in Excel.
- **DataFrame**: Two-dimensional table, similar to an Excel sheet or SQL table.

Pandas Series

A Series is a one-dimensional labeled array capable of holding any data type. The axis labels are collectively called the index.

Creating Series

There are multiple ways to create a pandas Series:

In [1]:
import numpy as np
import pandas as pd

In [2]:
label = ['a', 'b', 'c'] 
my_data = [10, 20, 30]
arr = np.array(my_data)
d = {'a': 10, 'b': 20, 'c': 30}

In [3]:
d

{'a': 10, 'b': 20, 'c': 30}

In [4]:
arr

array([10, 20, 30])

In [5]:
type(d)

dict

In [6]:
type(arr)

numpy.ndarray

In [7]:
type(my_data)

list

In [8]:
type(label)

list

Creating panadas series

In [3]:
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_data,index=label)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(data=my_data,index=label)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data=d)

a    10
b    20
c    30
dtype: int64

# 🐼 Pandas - DataFrame Basics
Welcome Today we’ll learn how to **inspect**, **select**, and **organize** data inside a DataFrame.

In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
pd.DataFrame(a,index=["a","b","c"],columns=["a","b","c"])

   a  b  c
a  1  2  3
b  4  5  6
c  7  8  9

In [8]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
labels = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=labels)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000


## 2 Selecting Columns & Rows
Ways to access parts of a DataFrame:
- Single column → `df['col']`
- Multiple columns → `df[['col1','col2']]`
- Label-based selection → `df.loc[row_label, col_label]`
- Integer-index selection → `df.iloc[row_idx, col_idx]`
Tip: `:` means "all rows/columns" in that dimension.

In [9]:
df2["Name"]# Accessing a single column
df2[["Name", "Age"]]# Accessing multiple columns

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [10]:
df2.loc[1]  # Selecting row with index 1
df2.loc[[0,2]]  # Selecting multiple rows with index 0 and iloc for position based indexing

    Name  Age      City  Salary
0   John   28  New York   65000
2  Peter   29    Berlin   62000

In [11]:
df.loc[[0,1]][["Name","Age"]] # Selecting subset of rows and columns

   Name  Age
0  John   28
1  Anna   34

## 3. Creating a new column

In [12]:
df2["Designation"]=["Manager", "Analyst", "Clerk", "Director"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000     Manager
1   Anna   34     Paris   70000     Analyst
2  Peter   29    Berlin   62000       Clerk
3  Linda   42    London   85000    Director

## 4.Removing Column and Rows
## Dropping Rows & Columns (`drop`)
- `drop(labels, axis=0)` → drop rows by index labels.
- `drop(labels, axis=1)` → drop columns by name.
- Use `inplace=True` if you want to modify the DataFrame directly.

In [13]:
df2.drop("Designation",axis=1, inplace=True) # Removing Column use inplace=True to make changes permanent and axis=0 for rows and 1 for columns
df2
df2.drop(["Name","Age"], axis=1) # Removing multiple columns and not used inplace=True so original df2 remains unchanged
df2
df2.drop(0, axis=0) # Removing Row with index 0
df2
df2.drop([1,2], axis=0) # Removing multiple rows with index
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## 5 Index & Columns Overview
- `df.index` → row labels
- `df.columns` → column names
- `df.values` → underlying NumPy array (read-only; prefer using DataFrame ops)

In [14]:
print(df.index)
print(df.columns)
print(df.values)

RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'City', 'Salary'], dtype='object')
[['John' 28 'New York' 65000]
 ['Anna' 34 'Paris' 70000]
 ['Peter' 29 'Berlin' 62000]
 ['Linda' 42 'London' 85000]]

## 6. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [15]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

## 7. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [23]:
df2[(df2["Age"]>30) & (df2["City"]=='London')]

    Name  Age    City  Salary
3  Linda   42  London   85000

## 8. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [24]:
df.query("Age>30")

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

## 9. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [25]:
df=df2
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df[df["Name"].str.contains("e",case=False)]

#like this you can use many string function

    Name  Age    City  Salary
2  Peter   29  Berlin   62000

## 10 Renaming Columns & Setting an Index
- Rename columns → `df.rename(columns={'old':'new'}, inplace=False)`
- Set a column as index → `df.set_index('column_name', inplace=False)`
- Reset index → `df.reset_index(inplace=False)`
 If you don't use `inplace=True`, remember to assign the result back to a variable.

In [17]:
df.rename(columns={"City":"State"},inplace=True)
df.set_index("Name",inplace=True)

In [18]:
df.reset_index(inplace=True)

In [29]:
df

    Name  Age     State  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Paris' or 'Berlin'.
4. Use query() to find rows with Score >= 85 and Age > 35.
5. Clean a text column using str.replace or str.lower or str.captalize.

In [30]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Score': [65, 70, 62, 85],
    'Text':['YES','NO','NO','YES']
}
df=pd.DataFrame(data)

df

    Name  Age      City  Score Text
0   John   28  New York     65  YES
1   Anna   34     Paris     70   NO
2  Peter   29    Berlin     62   NO
3  Linda   42    London     85  YES

In [31]:
df[df["Age"]>30]

    Name  Age    City  Score Text
1   Anna   34   Paris     70   NO
3  Linda   42  London     85  YES

In [32]:
df[(df["City"]=="Paris") | (df["City"]=="Berlin")]

    Name  Age    City  Score Text
1   Anna   34   Paris     70   NO
2  Peter   29  Berlin     62   NO

In [33]:
df.query(("Score>=85 and Age>35"))

    Name  Age    City  Score Text
3  Linda   42  London     85  YES

In [34]:
df["Text"]=df["Text"].str.capitalize()
df

    Name  Age      City  Score Text
0   John   28  New York     65  Yes
1   Anna   34     Paris     70   No
2  Peter   29    Berlin     62   No
3  Linda   42    London     85  Yes

# 🐼 Pandas - Data Cleaning Essentials
Welcome to our Pandas series. Today we’ll learn how to clean and prepare data for analysis.
## Handling Missing Values
Real-world datasets often have missing data. Pandas offers:
- `isna()` / `isnull()` → detect missing values (returns True/False)
- `dropna()` → remove missing values (rows/columns)
- `fillna()` → replace missing values with a given value or method (e.g., forward fill)

Always inspect how much data is missing before deciding to drop or fill.

In [19]:
import numpy as np
import pandas as pd

Finding missing data

In [25]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df=pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [26]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [27]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [28]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing missing data

In [40]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [29]:
df.dropna() # Drops any row with at least one NaN value

     A  B    C    D
0  1.0  1  1.0  1.0

In [30]:
df.dropna(thresh=3) # Drops any row with less than 3 non-NaN values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Filling missing data

In [43]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [45]:
values={"A":100,"B":200,"C":300,"D":400}
df.fillna(value=values)

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  400.0
2  100.0  3    3.0  400.0
3    4.0  4  300.0  400.0
4    5.0  5  300.0    5.0

In [46]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [47]:
df=df.fillna(df["D"].mean()) #fill with specific value

## Changing Data Types (`astype`)
- Convert a column to a different type using `astype()`.
- Examples: converting strings to numbers, integers to floats, or columns to category.

Be careful: make sure the data is compatible with the new type!

In [48]:
df["D"]=df["D"].astype(int) #change type of data
df

     A  B    C  D
0  1.0  1  1.0  1
1  2.0  2  2.0  3
2  3.0  3  3.0  3
3  4.0  4  3.0  3
4  5.0  5  3.0  5

In [49]:
d=df.copy()
d

     A  B    C  D
0  1.0  1  1.0  1
1  2.0  2  2.0  3
2  3.0  3  3.0  3
3  4.0  4  3.0  3
4  5.0  5  3.0  5

## Replacing Values (`replace`)
- Use `replace()` to substitute specific values or patterns.
- Useful for cleaning labels, fixing typos, or mapping categories.

In [50]:
d["A"]=d["A"].replace(1.0,10.0)
d

      A  B    C  D
0  10.0  1  1.0  1
1   2.0  2  2.0  3
2   3.0  3  3.0  3
3   4.0  4  3.0  3
4   5.0  5  3.0  5

Dropping rows and columns

In [51]:
d.drop([0,4],axis=0) #to drop the row

     A  B    C  D
1  2.0  2  2.0  3
2  3.0  3  3.0  3
3  4.0  4  3.0  3

In [52]:
d.drop("D",axis=1) #drop column

      A  B    C
0  10.0  1  1.0
1   2.0  2  2.0
2   3.0  3  3.0
3   4.0  4  3.0
4   5.0  5  3.0

## Detecting & Removing Duplicates
- `duplicated()` → returns a Boolean Series marking duplicate rows.
- `drop_duplicates()` → remove duplicate rows.
- You can specify `subset` (columns) and `keep` ('first', 'last', or False).

In [32]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda','Anna','Peter'],
    'Age': [28, 34, 29, 42,34,29],
    'City': ['New York', 'Paris', 'Berlin', 'London','Paris', 'Berlin'],
    'Salary': [65000, 70000, 62000, 85000,70000, 62000]
}

In [33]:
df=pd.DataFrame(data)

In [55]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000
4   Anna   34     Paris   70000
5  Peter   29    Berlin   62000

In [34]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [57]:
df.drop_duplicates(inplace=True)

In [58]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

## Mini Practice
1. Create a messy DataFrame with missing values, wrong data types, typos, extra columns, and duplicates.
2. Clean it step-by-step using what you learned:
   - Handle missing values
   - Change data types
   - Replace incorrect values
   - Drop unnecessary rows/columns
   - Remove duplicates

In [59]:
# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
df

Original messy DataFrame:

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [60]:
# filling missing values
print(df.isna().sum())
print(df.info())

Name     1
Age      1
City     0
Score    1
Extra    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      object
 2   City    6 non-null      object
 3   Score   5 non-null      float64
 4   Extra   6 non-null      object
dtypes: float64(1), object(4)
memory usage: 368.0+ bytes
None

In [61]:
df["Age"]=pd.to_numeric(df["Age"],errors="coerce") #we convert data into float then again to int then filled with mean
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Age"]=df["Age"].astype(int)

In [62]:
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai    NaN     y
2  Chrlie   30        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5    None   30     Mumbai   91.0     z

In [63]:
df["Name"]=df["Name"].fillna(df["Name"].mode()[0])
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai    NaN     y
2  Chrlie   30        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5   Alice   30     Mumbai   91.0     z

In [64]:
df["Score"]=df["Score"].fillna(df["Score"].mean())
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai   85.4     y
2  Chrlie   30        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5   Alice   30     Mumbai   91.0     z

In [65]:
# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed
df["City"]=df["City"].replace("Pun","Pune")
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai   85.4     y
2  Chrlie   30       Pune   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y
5   Alice   30     Mumbai   91.0     z

In [66]:
# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want
df.drop(columns="Extra",inplace=True)
df

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   85.4
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0
5   Alice   30     Mumbai   91.0

In [67]:
# 6. Remove duplicates
# Use duplicated() and drop_duplicates()
df.duplicated()
df.drop_duplicates(inplace=True)
df

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   85.4
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
5   Alice   30     Mumbai   91.0

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 200.0+ bytes

# 🐼 Pandas -Sorting & Basic Statistics
Welcome to our Pandas series. Today we’ll learn how to sort data and calculate basic statistics.

## 1. Sorting Data
- Use `sort_values(by='col')` to sort by column values.
- Use `ascending=False` for descending order.
- Sort by multiple columns by passing a list.
- `sort_index()` sorts by row or column index.

In [35]:
import pandas as pd
# New dataset
data = {
    "Product": ["Pen", "Notebook", "Pencil", "Marker", "Eraser", "Sharpener"],
    "Price": [10, 50, 5, 30, 8, 12],
    "Stock": [100, 60, 200, 80, 150, 120],
    "Rating": [4.5, 4.7, 4.2, 4.8, 4.3, 4.4]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
     Product  Price  Stock  Rating
0        Pen     10    100     4.5
1   Notebook     50     60     4.7
2     Pencil      5    200     4.2
3     Marker     30     80     4.8
4     Eraser      8    150     4.3
5  Sharpener     12    120     4.4

In [36]:
df.sort_values(by="Price",ascending=False)

     Product  Price  Stock  Rating
1   Notebook     50     60     4.7
3     Marker     30     80     4.8
5  Sharpener     12    120     4.4
0        Pen     10    100     4.5
4     Eraser      8    150     4.3
2     Pencil      5    200     4.2

In [71]:
df.sort_values(by=["Price","Stock"],ascending=[True,False])

     Product  Price  Stock  Rating
2     Pencil      5    200     4.2
4     Eraser      8    150     4.3
0        Pen     10    100     4.5
5  Sharpener     12    120     4.4
3     Marker     30     80     4.8
1   Notebook     50     60     4.7

## 2. Descriptive Statistics
- `mean()`, `median()`, `mode()` for central tendency.
- `std()` for standard deviation.
- `describe()` for a summary of stats (count, mean, std, min, quartiles, max).

In [37]:
df.mean(numeric_only=True)

Price      19.166667
Stock     118.333333
Rating      4.483333
dtype: float64

In [73]:
df.median(numeric_only=True)

Price      11.00
Stock     110.00
Rating      4.45
dtype: float64

In [38]:
df.std(numeric_only=True)

Price     17.486185
Stock     50.760877
Rating     0.231661
dtype: float64

In [39]:
df.describe()

           Price       Stock    Rating
count   6.000000    6.000000  6.000000
mean   19.166667  118.333333  4.483333
std    17.486185   50.760877  0.231661
min     5.000000   60.000000  4.200000
25%     8.500000   85.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.650000
max    50.000000  200.000000  4.800000

## 3. Counting Values
- `value_counts()` shows the frequency of unique values in a Series.
- Use `normalize=True` to see percentages instead of counts.

In [76]:
print(df["Product"].value_counts())
df["Product"].value_counts(normalize=True)

Product
Pen          1
Notebook     1
Pencil       1
Marker       1
Eraser       1
Sharpener    1
Name: count, dtype: int64

Product
Pen          0.166667
Notebook     0.166667
Pencil       0.166667
Marker       0.166667
Eraser       0.166667
Sharpener    0.166667
Name: proportion, dtype: float64

## 4. Correlation & Covariance
- `corr()` computes correlation between numeric columns.
- `cov()` computes covariance.
- Correlation values range from -1 (negative) to +1 (positive).

In [77]:
df.corr(numeric_only=True)

           Price     Stock    Rating
Price   1.000000 -0.804028  0.820402
Stock  -0.804028  1.000000 -0.921257
Rating  0.820402 -0.921257  1.000000

In [78]:
df.cov(numeric_only=True)

             Price        Stock     Rating
Price   305.766667  -713.666667   3.323333
Stock  -713.666667  2576.666667 -10.833333
Rating    3.323333   -10.833333   0.053667

In [79]:
df["Price"].corr(df["Rating"])

np.float64(0.8204016469535791)

## Mini Practice
1. Build a DataFrame with columns: Name, Age, Score, Height.
2. Sort the data by Score (descending).
3. Get mean, median, mode, and std of numeric columns.
4. Use value_counts on Name or any categorical column.
5. Compute corr() and cov() for all numeric columns.

In [80]:
data = {
    "Name": ["Liam", "Sophia", "Ethan", "Olivia", "Noah"],
    "Age": [27, 34, 29, 31, 26],
    "Score": [80, 95, 88, 76, 90],
    "Height": [172, 165, 180, 158, 175]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

     Name  Age  Score  Height
0    Liam   27     80     172
1  Sophia   34     95     165
2   Ethan   29     88     180
3  Olivia   31     76     158
4    Noah   26     90     175

In [81]:
df.sort_values(by="Score",ascending=False)

     Name  Age  Score  Height
1  Sophia   34     95     165
4    Noah   26     90     175
2   Ethan   29     88     180
0    Liam   27     80     172
3  Olivia   31     76     158

In [82]:
df.describe()

             Age      Score      Height
count   5.000000   5.000000    5.000000
mean   29.400000  85.800000  170.000000
std     3.209361   7.694154    8.631338
min    26.000000  76.000000  158.000000
25%    27.000000  80.000000  165.000000
50%    29.000000  88.000000  172.000000
75%    31.000000  90.000000  175.000000
max    34.000000  95.000000  180.000000

In [83]:
df["Name"].value_counts()

Name
Liam      1
Sophia    1
Ethan     1
Olivia    1
Noah      1
Name: count, dtype: int64

In [84]:
df.corr(numeric_only=True)

             Age     Score    Height
Age     1.000000  0.257155 -0.613694
Score   0.257155  1.000000  0.387738
Height -0.613694  0.387738  1.000000

In [85]:
df.cov(numeric_only=True)

          Age  Score  Height
Age     10.30   6.35  -17.00
Score    6.35  59.20   25.75
Height -17.00  25.75   74.50

---
## Summary
- Learned to sort by columns with `sort_values` and by index with `sort_index`.
- Explored descriptive statistics: mean, median, mode, std, describe.
- Counted values with `value_counts`.
- Calculated correlation and covariance.


# 🐼 Pandas - GroupBy & Aggregations
Welcome to our Pandas series. Today we’ll learn how to group data and perform aggregations.

In [86]:
import numpy as np 
import pandas as pd

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [87]:
# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [88]:
df["Department"].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

In [89]:
df.groupby("Department")["Salary"].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [90]:
df.groupby("Department")["Employee"].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [91]:
df.groupby("Department")["Salary"].agg(["max","mean","min"])

              max          mean    min
Department
Finance     65000  61000.000000  58000
HR          52000  51000.000000  50000
IT          75000  72333.333333  70000

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [92]:
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [93]:
df.groupby("Department").agg({
    "Salary":["max","mean","min"],
    "Age":["max","mean","min"]
})

           Salary                      Age
              max          mean    min max       mean min
Department
Finance     65000  61000.000000  58000  35  29.333333  26
HR          52000  51000.000000  50000  29  28.500000  28
IT          75000  72333.333333  70000  32  31.000000  30

## 1. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [94]:
import numpy as np 
import pandas as pd

Pivot Tables

In [95]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    431     20   John  January      Q1
1  2023-01-02       B   West    418     15   Mary  January      Q1
2  2023-01-03       C  North    886     95    Bob  January      Q1
3  2023-01-04       D  South    705     29  Alice  January      Q1
4  2023-01-05       A   East    382     77   John  January      Q1
5  2023-01-06       B   West    334     41   Mary  January      Q1
6  2023-01-07       C  North    410     90    Bob  January      Q1
7  2023-01-08       D  South    787     95  Alice  January      Q1
8  2023-01-09       A   East    482     43   John  January      Q1
9  2023-01-10       B   West    355     11   Mary  January      Q1
10 2023-01-11       C  North    358     99    Bob  January      Q1
11 2023-01-12       D  South    401     38  Alice  January      Q1
12 2023-01-13       A   East    888     22   John  January      Q1
13 2023-01-14       B   West    409     96   Mary  January      Q1
14 2023-01-15       C  North    389     88    Bob  January      Q1
15 2023-01-16       D  South    429     47  Alice  January      Q1
16 2023-01-17       A   East    328     71   John  January      Q1
17 2023-01-18       B   West    848     30   Mary  January      Q1
18 2023-01-19       C  North    843     45    Bob  January      Q1
19 2023-01-20       D  South    106     91  Alice  January      Q1

In [96]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product",aggfunc="sum")

Product       A       B       C       D
Region
East     2511.0     NaN     NaN     NaN
North       NaN     NaN  2886.0     NaN
South       NaN     NaN     NaN  2428.0
West        NaN  2364.0     NaN     NaN

In [97]:
pd.pivot_table(df,values=["Sales","Units"],index="Region",columns="Product",aggfunc="sum")

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     2511.0     NaN     NaN     NaN  233.0    NaN    NaN    NaN
North       NaN     NaN  2886.0     NaN    NaN    NaN  417.0    NaN
South       NaN     NaN     NaN  2428.0    NaN    NaN    NaN  300.0
West        NaN  2364.0     NaN     NaN    NaN  193.0    NaN    NaN

Cross Tabs

In [98]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

# 🐼 Pandas - Merging, Joining & Concatenation
Welcome too our Pandas series. Today we’ll learn how to combine multiple DataFrames using different techniques.

In [99]:
import numpy as np
import pandas as pd

## 1. Using `merge()` for SQL-Style Joins
- `merge()` is similar to SQL joins.
- Specify `on` or `left_on`/`right_on` to choose key columns.
- Join types: `inner` (default), `left`, `right`, `outer`.

Merging 2 dataframes

In [100]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [101]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [102]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [103]:
pd.merge(employees,salaries,how="inner",on="employee_id")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [104]:
pd.merge(employees,salaries,how="outer",on="employee_id")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [105]:
pd.merge(employees,salaries,how="left",on="employee_id")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [106]:
pd.merge(employees,salaries,how="right",on="employee_id")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

## 2. Using `concat()` for Stacking Data
- `pd.concat()` combines DataFrames vertically (rows) or horizontally (columns).
- Use `axis=0` for vertical stacking (default), `axis=1` for horizontal.
- `ignore_index=True` can reset the index after concatenation.

Concatination of 2 dataframes

In [107]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [108]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [109]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [110]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [111]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

## 3. Using `join()` with Index Alignment
- `join()` joins DataFrames on their index or on a key column.
- By default, joins on index; can specify `on='col'`.
- Useful for adding columns to an existing DataFrame.

Joining 2 data frames

In [112]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [113]:
df1.join(df2,how="inner")

      name  score
2      Bob     85
3  Charlie     90

# 🐼 Pandas - Working with Time Series
Welcome to our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [114]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# 2. Convert the 'OrderDate' column to datetime
df["OrderDate"] = pd.to_datetime(df["OrderDate"], dayfirst=True, errors="coerce")
print("\nAfter converting OrderDate to datetime:")
print(df)

# 3. Verify data types
print("\nData types after conversion:")
print(df.dtypes)

# 4. (Optional) Handle any rows where conversion failed
if df["OrderDate"].isna().any():
    print("\nRows with invalid dates:")
    print(df[df["OrderDate"].isna()])

Original DataFrame:
   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

After converting OrderDate to datetime:
   OrderID  OrderDate Customer  Amount
0     1001 2024-05-01    Alice     250
1     1002        NaT      Bob     400
2     1003        NaT  Charlie     150
3     1004        NaT    David     300
4     1005        NaT     Emma     500

Data types after conversion:
OrderID               int64
OrderDate    datetime64[ns]
Customer             object
Amount                int64
dtype: object

Rows with invalid dates:
   OrderID OrderDate Customer  Amount
1     1002       NaT      Bob     400
2     1003       NaT  Charlie     150
3     1004       NaT    David     300
4     1005       NaT     Emma     500

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [115]:

# 1️⃣ Convert OrderDate to datetime
df["OrderDate"] = pd.to_datetime(df["OrderDate"], dayfirst=True, errors="coerce")
print("DataFrame after converting dates:")
print(df)

# 2️⃣ Set OrderDate as the index
df_idx = df.set_index("OrderDate")
print("\nDataFrame with OrderDate as index:")
print(df_idx)

# 3️⃣ Resample by month to compute total Amount per month
monthly_total = df_idx.resample("M")["Amount"].sum()
print("\nTotal Amount per month:")
print(monthly_total)

# 4️⃣ Resample by week to compute average Amount per week
weekly_avg = df_idx.resample("W")["Amount"].mean()
print("\nAverage Amount per week:")
print(weekly_avg)

DataFrame after converting dates:
   OrderID  OrderDate Customer  Amount
0     1001 2024-05-01    Alice     250
1     1002        NaT      Bob     400
2     1003        NaT  Charlie     150
3     1004        NaT    David     300
4     1005        NaT     Emma     500

DataFrame with OrderDate as index:
            OrderID Customer  Amount
OrderDate
2024-05-01     1001    Alice     250
NaT            1002      Bob     400
NaT            1003  Charlie     150
NaT            1004    David     300
NaT            1005     Emma     500

Total Amount per month:
OrderDate
2024-05-31    250
Name: Amount, dtype: int64

Average Amount per week:
OrderDate
2024-05-05    250.0
Name: Amount, dtype: float64

C:\Users\ABH\AppData\Local\Temp\ipykernel_32276\3155173877.py:12: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_total = df_idx.resample("M")["Amount"].sum()

In [116]:

# 2️⃣ Convert OrderDate to datetime
df["OrderDate"] = pd.to_datetime(df["OrderDate"], dayfirst=True, errors="coerce")
print("\nAfter converting to datetime:")
print(df)

# 3️⃣ Set OrderDate as the index
df = df.set_index("OrderDate")
print("\nDataFrame with DateTime index:")
print(df)

# 4️⃣ Slice all orders in January 2024
print("\nOrders in January 2024:")
print(df.loc["2024-01"])

# 5️⃣ Slice a specific date range
# print("\nOrders from 2024-01-10 to 2024-01-20:")
# print(df.loc["2024-01-10":"2024-01-20"])

# 6️⃣ Filter with condition: Amount > 300 after Jan 12
print("\nOrders after 2024-01-12 with Amount > 300:")
print(df[(df.index > "2024-01-12") & (df["Amount"] > 300)])

After converting to datetime:
   OrderID  OrderDate Customer  Amount
0     1001 2024-05-01    Alice     250
1     1002        NaT      Bob     400
2     1003        NaT  Charlie     150
3     1004        NaT    David     300
4     1005        NaT     Emma     500

DataFrame with DateTime index:
            OrderID Customer  Amount
OrderDate
2024-05-01     1001    Alice     250
NaT            1002      Bob     400
NaT            1003  Charlie     150
NaT            1004    David     300
NaT            1005     Emma     500

Orders in January 2024:
Empty DataFrame
Columns: [OrderID, Customer, Amount]
Index: []

Orders after 2024-01-12 with Amount > 300:
Empty DataFrame
Columns: [OrderID, Customer, Amount]
Index: []

In [117]:
# TASK: Use rolling() to compute a moving average.
# Use expanding() to calculate cumulative metrics.

## mini-project 

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [118]:
import pandas as pd

# 1️⃣ Create a dataset of website visits (string dates + visit counts)
data = {
    "VisitDate": [
        "2024-01-03", "2024/01/08", "15-01-2024", "2024-02-02",
        "2024-02-15", "2024/03/01", "2024-03-12", "01-04-2024"
    ],
    "Visitors": [120, 150, 90, 200, 180, 220, 210, 300]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# 2️⃣ Convert VisitDate to datetime
df["VisitDate"] = pd.to_datetime(df["VisitDate"], dayfirst=True, errors="coerce")
print("\nAfter converting VisitDate to datetime:")
print(df)

# 3️⃣ Set VisitDate as the index
df = df.set_index("VisitDate")
print("\nDataFrame with VisitDate as index:")
print(df)

# 4️⃣ Resample to get total visitors per month
monthly_total = df.resample("M")["Visitors"].sum()
print("\nTotal visitors per month:")
print(monthly_total)

# 5️⃣ Resample to get average visitors per week
weekly_avg = df.resample("W")["Visitors"].mean()
print("\nAverage visitors per week:")
print(weekly_avg)

Original DataFrame:
    VisitDate  Visitors
0  2024-01-03       120
1  2024/01/08       150
2  15-01-2024        90
3  2024-02-02       200
4  2024-02-15       180
5  2024/03/01       220
6  2024-03-12       210
7  01-04-2024       300

After converting VisitDate to datetime:
   VisitDate  Visitors
0 2024-03-01       120
1        NaT       150
2        NaT        90
3 2024-02-02       200
4        NaT       180
5        NaT       220
6 2024-12-03       210
7        NaT       300

DataFrame with VisitDate as index:
            Visitors
VisitDate
2024-03-01       120
NaT              150
NaT               90
2024-02-02       200
NaT              180
NaT              220
2024-12-03       210
NaT              300

Total visitors per month:
VisitDate
2024-02-29    200
2024-03-31    120
2024-04-30      0
2024-05-31      0
2024-06-30      0
2024-07-31      0
2024-08-31      0
2024-09-30      0
2024-10-31      0
2024-11-30      0
2024-12-31    210
Name: Visitors, dtype: int64

Average visitors per week:
VisitDate
2024-02-04    200.0
2024-02-11      NaN
2024-02-18      NaN
2024-02-25      NaN
2024-03-03    120.0
2024-03-10      NaN
2024-03-17      NaN
2024-03-24      NaN
2024-03-31      NaN
2024-04-07      NaN
2024-04-14      NaN
2024-04-21      NaN
2024-04-28      NaN
2024-05-05      NaN
2024-05-12      NaN
2024-05-19      NaN
2024-05-26      NaN
2024-06-02      NaN
2024-06-09      NaN
2024-06-16      NaN
2024-06-23      NaN
2024-06-30      NaN
2024-07-07      NaN
2024-07-14      NaN
2024-07-21      NaN
2024-07-28      NaN
2024-08-04      NaN
2024-08-11      NaN
2024-08-18      NaN
2024-08-25      NaN
2024-09-01      NaN
2024-09-08      NaN
2024-09-15      NaN
2024-09-22      NaN
2024-09-29      NaN
2024-10-06      NaN
2024-10-13      NaN
2024-10-20      NaN
2024-10-27      NaN
2024-11-03      NaN
2024-11-10      NaN
2024-11-17      NaN
2024-11-24      NaN
2024-12-01      NaN
2024-12-08    210.0
Name: Visitors, dtype: float64

C:\Users\ABH\AppData\Local\Temp\ipykernel_32276\2301235547.py:27: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_total = df.resample("M")["Visitors"].sum()

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.

# 🐼 Pandas - Advanced Tricks & Performance
Welcome to our Pandas series. Today we’ll explore advanced techniques to write efficient, clean, and optimized Pandas code.

In [119]:
import numpy as np 
import pandas as pd

In [120]:
# DataFrames Basic Operations

## 1 Inspecting Data
Quick ways to understand your dataset:
- `head(n)` → first *n* rows (default 5)
- `tail(n)` → last *n* rows
- `info()` → columns, non-null counts, and dtypes
- `shape` → (rows, columns)
- `dtypes` → data type of each column

In [123]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [124]:
df1.dtypes

A    int64
B    int64
C    int64
dtype: object

In [125]:
df1.head(5)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [126]:
df1.tail(2)

   A   B    C
3  4  40  400
4  5  50  500

In [127]:
df1.shape

(5, 3)

In [128]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [129]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 248.0 bytes

In [130]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

## 1. Applying Custom Functions with `apply()` / `map()`
- `apply()` lets you apply a custom function across rows or columns.
- `map()` is for applying functions element-wise to a Series.
- Both are handy for transformations, calculations, and cleaning data.

In [133]:
import pandas as pd 
import numpy as np 
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Math": [88, 75, 92, 60, 85],
    "Science": [90, 80, 78, 70, 95]
}

df = pd.DataFrame(data)

In [134]:
df["Total_marks"]=df[["Math","Science"]].apply(lambda row:row.sum(),axis=1)
df

      Name  Math  Science  Total_marks
0    Alice    88       90          178
1      Bob    75       80          155
2  Charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [135]:
col_mean=df[["Math","Science"]].apply(lambda col:col.mean(),axis=0)
col_mean

Math       80.0
Science    82.6
dtype: float64

In [136]:
def to_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"
df["Math Grade"]=df["Math"].apply(to_grade)
df

      Name  Math  Science  Total_marks Math Grade
0    Alice    88       90          178          B
1      Bob    75       80          155          C
2  Charlie    92       78          170          A
3    David    60       70          130          D
4     Emma    85       95          180          B